### PR TITLE
Include initrd mounts in the final system also

### LINKED ISSUE #2: Error on shutdown unmounting /var/log
I get the following error on shutdown
```
sep 07 15:11:57 framework systemd[1]: var-log.mount: Mount process exited, code=exited, status=32/n/a
sep 07 15:11:57 framework systemd[1]: Failed unmounting var-log.mount.
```
Since it's at shutdown, I can't inspect the system state when this happens. Probably we'd need some ordering to make sure that we only unmount this after journalctl stopped?

I configured it like in the examples, with `{ directory = "/var/log"; inInitrd = true; }`

### PR DESCRIPTION
**Pull request by r-vdp**
Without this, things like `RequiresMountsFor` do not work correctly during shutdown.

See https://github.com/systemd/systemd/pull/34327

Fixes #2

### CODE REVIEW

**Comment by WilliButz** [comment]
It seems like this change would re-introduce the ordering cycle for `var-log.mount`, `systemd-journal-flush.service`, and `systemd-tmpfiles-setup.service` (described in [TODO.md)](https://github.com/WilliButz/preservation/blob/02e731a820d05107bc648460f8630d0d80a5ffd4/TODO.md?plain=1#L16-L33).

Adding an entry in the integration test for /var/log with `inInitrd=true` should cause log messages about the ordering cycle to appear.

I'm not sure yet how to resolve this, other than the solution described at the end of the linked file.

**Comment by r-vdp** [comment]
I booted my system with this and didn't get any mention of a cycle in my logs.

**Comment by r-vdp** [comment]
The mount is still set up in initrd as before, it's just that we include the unit in the final system as well so that systemd takes it into account and uses the right ordering when unmounting.
Nothing gets remounted or such.

**Comment by WilliButz** [comment]
> I booted my system with this and didn't get any mention of a cycle in my logs

I just pushed [another branch based on yours](https://github.com/WilliButz/preservation/commits/ordering-cycle-demo/) where `/var/log` is also preserved in the test, here you can see the log messages that show the described ordering cycle:
https://github.com/WilliButz/preservation/actions/runs/10808159129/job/29980512998#step:5:1813

**Comment by r-vdp** [comment]
It's so weird that I don't have that cycle on my systems, I just checked again. I have the whole shutdown sequence in the logs and there's no mention of any cycle. I will try to find out what is different, something in my config must be preventing this cycle. I'm running nixos-unstable (with a bunch of unmerged PRs patched in).

I already notice that actually now there isn't any mention of unmounting /var/log or /var/lib on shutdown of my machine, neither of stopping systemd-journal-flush. They might only get unmounted after the journal already stopped, since the last message that I have is "Journal stopped".

**Comment by WilliButz** [comment]
This should be solved by 97104c042dfa36e24659db05976409294d774ee5.
Now `/var/log` is also included in the test and it no longer needs `inInitrd = true` to avoid the ordering cycle.

**Comment by r-vdp** [comment]
Seems to be working well now, thanks!

**Pull request closed without merging**
